server:
  port: 8080
spring:
  application:
    name: "msc-autenticacion"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

springdoc:
  swagger-ui:
    path: "/api/doc/swagger-ui.html"
  api-docs:
    path: "/api/doc/api-docs"

routes:
  paths:
    users:
      users: "/api/v1/users"
      userByEmail: "/api/v1/user/{email}"
      userByIdentification: "/api/v1/users/{identification}"
      emailByIdentification: "/api/v1/users/email/{identification}"
    auth:
      login: "/api/v1/login"
      validateUser: "/api/v1/auth"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "msc_autenticacion"
    schema: "public"
    username: "admin"
    password: "adminpassword"