server:
  port: 8080
spring:
  application:
    name: "autenticacion"
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

springdoc:
  swagger-ui:
    path: "/api/doc/swagger-ui.html"
  api-docs:
    path: "/api/doc/api-docs"

routes:
  paths:
    users:
      users: "/api/v1/users"
      userByEmail: "/api/v1/user/{email}"
      userByIdentification: "/api/v1/users/{identification}"
      emailByIdentification: "/api/v1/users/email/{identification}"
    auth:
      login: "/api/v1/login"
      validateUser: "/api/v1/auth"

adapters:
  r2dbc:
    host: "${R2DBC_HOST}"
    port: "${R2DBC_PORT}"
    database: "${R2DBC_DATABASE}"
    schema: "${R2DBC_SCHEMA}"
    username: "${R2DBC_USERNAME}"
    password: "${R2DBC_PASSWORD}"

jwt:
  secret: "${JWT_SECRET}"
  expiration-ms: "${JWT_EXPIRATION}"